version: "3.9"

services:
  backend:
    build: ./nayaview-anime-back
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  frontend:
    build: ./nayaview-anime-front
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./certs:/etc/ssl/certs:ro
    env_file:
      - ./.env

  analytics:
    build: ./analytics
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:17-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  db_data:
